"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { MOCK_LOT_MANAGER } from "@/lib/seller/seller-mock-data";

const POLL_INTERVAL_MS = 2_000;
const MAX_BODY_LEN = 4000;

interface ChatMessage {
  id: string;
  author: "seller" | "support";
  authorName: string;
  body: string;
  createdAt: string;
}

interface RealDocument {
  id: string;
  documentType: string;
  title: string;
  cdnUrl: string | null;
  signedAt: string | null;
  createdAt: string;
}

// Documents that the seller will receive *after* the sale completes — shown
// greyed-out so the seller knows what's coming. Static because they're
// generated by the platform, not uploaded.
const POST_SALE_DOCS = [
  { id: "ps-sale-confirm", title: "Sale confirmation",  meta: "Available once sale completes", iconText: "SA", iconBg: "#F7F8F9", iconColor: "#8492A8" },
  { id: "ps-net-sheet",    title: "Final net sheet",    meta: "Exact payout breakdown — available at close", iconText: "NS", iconBg: "#F7F8F9", iconColor: "#8492A8" },
];

const DOC_ICON_BY_TYPE: Record<string, { iconText: string; iconBg: string; iconColor: string }> = {
  consignment_agreement: { iconText: "CA",  iconBg: "#E0FAF5", iconColor: "#006058" },
  hpi_check:             { iconText: "HPI", iconBg: "#D1FAE5", iconColor: "#064E3B" },
  condition_report:      { iconText: "CR",  iconBg: "#DBEAFE", iconColor: "#1E40AF" },
  v5c_logbook:           { iconText: "V5",  iconBg: "#FFF8E6", iconColor: "#92400E" },
  service_history:       { iconText: "SH",  iconBg: "#FEF3C7", iconColor: "#92400E" },
  sale_invoice:          { iconText: "SI",  iconBg: "#E0FAF5", iconColor: "#006058" },
};

const DOC_TITLE_OVERRIDE: Record<string, string> = {
  consignment_agreement: "Consignment agreement",
  hpi_check:             "HPI check certificate",
  condition_report:      "Condition report",
  v5c_logbook:           "V5C logbook",
  service_history:       "Service history",
  sale_invoice:          "Sale invoice",
};

function docIcon(type: string) {
  return DOC_ICON_BY_TYPE[type] ?? { iconText: type.slice(0, 2).toUpperCase(), iconBg: "#F7F8F9", iconColor: "#8492A8" };
}

function docMeta(d: RealDocument): string {
  const created = new Date(d.createdAt).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
  const signed  = d.signedAt ? new Date(d.signedAt).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" }) : null;
  if (d.documentType === "v5c_logbook") return "Held by iAutoMotive · Transfer notified to DVLA at point of sale";
  return signed ? `Signed ${signed} · PDF` : `Added ${created} · PDF`;
}

export default function SellerDocumentsPage() {
  const [docs, setDocs] = useState<RealDocument[]>([]);
  const [docsLoaded, setDocsLoaded] = useState(false);

  useEffect(() => {
    fetch("/api/seller/me")
      .then(r => r.ok ? r.json() : null)
      .then(d => { if (d?.documents) setDocs(d.documents); })
      .finally(() => setDocsLoaded(true));
  }, []);

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState("");
  const [sending, setSending] = useState(false);
  const [authError, setAuthError] = useState<string | null>(null);
  const messagesRef = useRef<HTMLDivElement>(null);
  // Tracks the latest message timestamp so the poll only asks for "new since X".
  const sinceRef = useRef<string | null>(null);

  const fetchMessages = useCallback(async () => {
    try {
      const url = sinceRef.current
        ? `/api/seller/support?since=${encodeURIComponent(sinceRef.current)}`
        : "/api/seller/support";
      const res = await fetch(url, { cache: "no-store" });
      if (res.status === 401) {
        setAuthError("Sign in to your seller account to chat with support.");
        return;
      }
      if (!res.ok) return;
      const data: { messages: ChatMessage[] } = await res.json();
      if (data.messages.length === 0) return;
      setMessages(prev => {
        // De-dup by id — server can return overlapping rows on the first call.
        const seen = new Set(prev.map(m => m.id));
        const merged = [...prev];
        for (const m of data.messages) if (!seen.has(m.id)) merged.push(m);
        return merged;
      });
      sinceRef.current = data.messages[data.messages.length - 1].createdAt;
      setAuthError(null);
    } catch (err) {
      // Network blip — next tick will retry; don't surface intermittent errors.
      console.error("[seller chat poll]", err);
    }
  }, []);

  // Initial fetch + 2s polling.
  useEffect(() => {
    let cancelled = false;
    let timer: ReturnType<typeof setInterval> | null = null;
    (async () => {
      await fetchMessages();
      if (cancelled) return;
      timer = setInterval(fetchMessages, POLL_INTERVAL_MS);
    })();
    return () => {
      cancelled = true;
      if (timer) clearInterval(timer);
    };
  }, [fetchMessages]);

  // Auto-scroll when messages change
  useEffect(() => {
    messagesRef.current?.scrollTo({
      top: messagesRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [messages]);

  const handleSend = async () => {
    const body = inputValue.trim();
    if (!body || sending) return;
    if (body.length > MAX_BODY_LEN) return;
    setSending(true);
    try {
      const res = await fetch("/api/seller/support", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ body }),
      });
      if (res.status === 401) {
        setAuthError("Sign in to your seller account to chat with support.");
        return;
      }
      if (!res.ok) return;
      const data: { message: ChatMessage } = await res.json();
      setMessages(prev => [...prev, data.message]);
      sinceRef.current = data.message.createdAt;
      setInputValue("");
    } catch (err) {
      console.error("[seller chat send]", err);
    } finally {
      setSending(false);
    }
  };

  return (
    <div style={{ fontFamily: "var(--font-body)" }}>
      {/* ── Section 1: Available Documents ── */}
      <div
        style={{
          background: "#FFFFFF",
          borderRadius: "16px",
          border: "1px solid #E2E8F0",
          padding: "20px",
          marginBottom: "16px",
        }}
      >
        <div
          style={{
            fontFamily: "var(--font-body)",
            fontWeight: 700,
            fontSize: "11px",
            color: "#94A3B8",
            textTransform: "uppercase",
            letterSpacing: "0.1em",
            marginBottom: "12px",
          }}
        >
          YOUR DOCUMENTS
        </div>

        {!docsLoaded && (
          <div style={{ fontSize: 12, color: "#94A3B8", padding: "12px 0" }}>Loading documents…</div>
        )}
        {docsLoaded && docs.length === 0 && (
          <div style={{ fontSize: 12, color: "#94A3B8", padding: "12px 0" }}>
            Nothing yet — your documents will appear here as we collect them through intake.
          </div>
        )}
        {docs.map((doc, i) => {
          const icon = docIcon(doc.documentType);
          const title = DOC_TITLE_OVERRIDE[doc.documentType] ?? doc.title;
          const isHeld = doc.documentType === "v5c_logbook";
          return (
            <div
              key={doc.id}
              style={{
                display: "flex", alignItems: "center", gap: "14px", padding: "12px 0",
                borderBottom: i < docs.length - 1 ? "1px solid #F7F8F9" : "none",
              }}
            >
              <div
                style={{
                  width: 36, height: 36, borderRadius: 12,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontFamily: "var(--font-body)", fontWeight: 700, fontSize: 13,
                  background: icon.iconBg, color: icon.iconColor, flexShrink: 0,
                }}
              >
                {icon.iconText}
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontFamily: "var(--font-body)", fontWeight: 700, fontSize: 13, color: "#1E293B", marginBottom: 2 }}>
                  {title}
                </div>
                <div style={{ fontFamily: "var(--font-body)", fontWeight: 400, fontSize: 12, color: "#94A3B8" }}>
                  {docMeta(doc)}
                </div>
              </div>
              {isHeld ? (
                <button disabled
                  style={{
                    background: "#F7F8F9", border: "1px solid #E2E8F0", borderRadius: 9999,
                    padding: "6px 14px", fontFamily: "var(--font-body)", fontWeight: 600, fontSize: 12,
                    color: "#64748B", cursor: "default", opacity: 0.5, pointerEvents: "none",
                  }}
                >
                  On sale
                </button>
              ) : doc.cdnUrl ? (
                <a href={doc.cdnUrl} target="_blank" rel="noreferrer"
                  style={{
                    background: "#F7F8F9", border: "1px solid #E2E8F0", borderRadius: 9999,
                    padding: "6px 14px", fontFamily: "var(--font-body)", fontWeight: 600, fontSize: 12,
                    color: "#64748B", cursor: "pointer", textDecoration: "none",
                  }}
                >
                  Download
                </a>
              ) : (
                <span style={{
                  background: "#F7F8F9", border: "1px solid #E2E8F0", borderRadius: 9999,
                  padding: "6px 14px", fontFamily: "var(--font-body)", fontWeight: 600, fontSize: 12,
                  color: "#94A3B8",
                }}>
                  Pending file
                </span>
              )}
            </div>
          );
        })}
      </div>

      {/* ── Section 2: Pending Documents ── */}
      <div
        style={{
          background: "#FFFFFF",
          borderRadius: "16px",
          border: "1px solid #E2E8F0",
          padding: "20px",
          marginBottom: "16px",
          opacity: 0.6,
        }}
      >
        <div
          style={{
            fontFamily: "var(--font-body)",
            fontWeight: 700,
            fontSize: "11px",
            color: "#94A3B8",
            textTransform: "uppercase",
            letterSpacing: "0.1em",
            marginBottom: "12px",
          }}
        >
          AFTER YOUR CAR SELLS
        </div>

        {POST_SALE_DOCS.map((doc, i) => (
          <div
            key={doc.id}
            style={{
              display: "flex", alignItems: "center", gap: "14px", padding: "12px 0",
              borderBottom: i < POST_SALE_DOCS.length - 1 ? "1px solid #F7F8F9" : "none",
            }}
          >
            <div
              style={{
                width: 36, height: 36, borderRadius: 12,
                display: "flex", alignItems: "center", justifyContent: "center",
                fontFamily: "var(--font-body)", fontWeight: 700, fontSize: 13,
                background: doc.iconBg, color: doc.iconColor, flexShrink: 0,
              }}
            >
              {doc.iconText}
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontFamily: "var(--font-body)", fontWeight: 700, fontSize: 13, color: "#1E293B", marginBottom: 2 }}>
                {doc.title}
              </div>
              <div style={{ fontFamily: "var(--font-body)", fontWeight: 400, fontSize: 12, color: "#94A3B8" }}>
                {doc.meta}
              </div>
            </div>
            <span
              style={{
                background: "#E2E8F0", color: "#94A3B8", borderRadius: 9999,
                padding: "4px 12px", fontFamily: "var(--font-body)", fontWeight: 600, fontSize: 11,
              }}
            >
              Pending
            </span>
          </div>
        ))}
      </div>

      {/* ── Section 3: Messaging Panel ── */}
      <div
        id="messaging"
        style={{
          background: "#FFFFFF",
          borderRadius: "16px",
          border: "1px solid #E2E8F0",
          overflow: "hidden",
          marginBottom: "16px",
        }}
      >
        {/* Header */}
        <div
          style={{
            background: "#008C7C",
            padding: "14px 18px",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <div>
            <div
              style={{
                fontFamily: "var(--font-body)",
                fontWeight: 700,
                fontSize: "14px",
                color: "#FFFFFF",
              }}
            >
              Your iAutoMotive contact
            </div>
            <div
              style={{
                fontFamily: "var(--font-body)",
                fontWeight: 400,
                fontSize: "11px",
                color: "#FFFFFF",
                opacity: 0.75,
              }}
            >
              {MOCK_LOT_MANAGER.name} — {MOCK_LOT_MANAGER.role},{" "}
              {MOCK_LOT_MANAGER.location}
            </div>
          </div>
          <span
            style={{
              background: "rgba(255,255,255,0.2)",
              borderRadius: "9999px",
              padding: "2px 8px",
              fontFamily: "var(--font-body)",
              fontWeight: 700,
              fontSize: "10px",
              color: "#FFFFFF",
            }}
          >
            {MOCK_LOT_MANAGER.responseTime}
          </span>
        </div>

        {/* Message body */}
        <div
          ref={messagesRef}
          style={{
            padding: "16px",
            maxHeight: "220px",
            overflowY: "auto",
            display: "flex",
            flexDirection: "column",
            gap: "8px",
          }}
        >
          {authError && messages.length === 0 && (
            <div
              style={{
                fontFamily: "var(--font-body)",
                fontSize: 13,
                color: "#94A3B8",
                textAlign: "center",
                padding: "24px 0",
              }}
            >
              {authError}
            </div>
          )}
          {!authError && messages.length === 0 && (
            <div
              style={{
                fontFamily: "var(--font-body)",
                fontSize: 13,
                color: "#94A3B8",
                textAlign: "center",
                padding: "24px 0",
              }}
            >
              Send a message and our support team will reply here in real-time.
            </div>
          )}
          {messages.map((msg, i) => {
            const showLabel = msg.author !== messages[i - 1]?.author;
            const isMe = msg.author === "seller";

            return (
              <div key={msg.id}>
                {showLabel && (
                  <div
                    style={{
                      fontFamily: "var(--font-body)",
                      fontWeight: 600,
                      fontSize: "11px",
                      color: "#94A3B8",
                      marginBottom: "4px",
                      textAlign: isMe ? "right" : "left",
                    }}
                  >
                    {isMe ? "You" : msg.authorName || "Support"}
                  </div>
                )}
                <div
                  style={{
                    background: isMe ? "#E0FAF5" : "#F7F8F9",
                    color: isMe ? "#006058" : "#1E293B",
                    borderRadius: isMe
                      ? "12px 12px 4px 12px"
                      : "12px 12px 12px 4px",
                    padding: "10px 14px",
                    fontFamily: "var(--font-body)",
                    fontWeight: 400,
                    fontSize: "13px",
                    lineHeight: "1.625",
                    maxWidth: "85%",
                    marginLeft: isMe ? "auto" : undefined,
                    whiteSpace: "pre-wrap",
                  }}
                >
                  {msg.body}
                </div>
              </div>
            );
          })}
        </div>

        {/* Input row */}
        <div
          style={{
            borderTop: "1px solid #E2E8F0",
            padding: "12px",
            display: "flex",
            gap: "8px",
          }}
        >
          <input
            type="text"
            placeholder="Message Tom..."
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") handleSend();
            }}
            style={{
              flex: 1,
              background: "#FFFFFF",
              border: "1px solid #E2E8F0",
              borderRadius: "9999px",
              padding: "8px 16px",
              fontFamily: "var(--font-body)",
              fontWeight: 400,
              fontSize: "13px",
              color: "#1E293B",
              outline: "none",
            }}
            onFocus={(e) => {
              e.currentTarget.style.borderColor = "#008C7C";
            }}
            onBlur={(e) => {
              e.currentTarget.style.borderColor = "#E2E8F0";
            }}
          />
          <button
            onClick={handleSend}
            disabled={sending || !inputValue.trim()}
            style={{
              background: "#008C7C",
              color: "#FFFFFF",
              borderRadius: "9999px",
              padding: "8px 16px",
              fontFamily: "var(--font-body)",
              fontWeight: 700,
              fontSize: "12px",
              cursor: sending || !inputValue.trim() ? "not-allowed" : "pointer",
              border: "none",
              opacity: sending || !inputValue.trim() ? 0.55 : 1,
            }}
          >
            {sending ? "Sending…" : "Send"}
          </button>
        </div>
      </div>
    </div>
  );
}
